// src/contexts/LanguageContext.js
import { createContext, useState } from 'react';

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('uk');

  const translations = {
    uk: {
      header: {
        home: 'Головна сторінка',
        contacts: 'Контакти',
        loginBtn: 'Увійти',
        signupBtn: 'Почати безкоштовно',
        logoText: 'mikitchTask',
        myProfile: 'Мій профіль ▼',
        profile: 'Профіль',
        myBookings: 'Мої бронювання',
        allBookings: 'Всі бронювання',
        logout: 'Вийти',
      },
      theme: {
  light: 'Світла',
  dark: 'Темна',
  switchToLight: 'Перемкнути на світлу тему',
  switchToDark: 'Перемкнути на темну тему'
},
      login: {
        title: 'Увійти',
        invalidCredentials: 'Невірний email або пароль',
        noAccount: 'Не маєте акаунта?',
        register: 'Зареєструватися',
      },
      register: {
        title: 'Створити акаунт',
        alreadyHaveAccount: 'Вже маєте акаунт?',
        login: 'Увійти',
      },
      footer: {
        subscribe: 'Підпишіться на нашу розсилку для останніх функцій та оновлень.',
        emailPlaceholder: 'Ваш email тут',
        join: 'Приєднатися',
        consent: 'Підписуючись, ви погоджуєтесь з нашою Політикою конфіденційності та отримуєте оновлення.',
        usefulLinks: 'Корисні посилання',
        aboutUs: 'Про нас',
        contactUs: 'Зв’язатися з нами',
        support: 'Підтримка',
        careers: 'Кар’єра',
        blog: 'Блог',
        resources: 'Ресурси',
        helpCenter: 'Центр допомоги',
        apiDocs: 'Документація API',
        community: 'Спільнота',
        feedback: 'Зворотний зв’язок',
        events: 'Події',
        connectWithUs: 'Зв’яжіться з нами',
        copyright: '© 2025 Relume. Всі права захищені.',
        privacy: 'Політика конфіденційності',
        terms: 'Умови обслуговування',
        cookie: 'Налаштування cookies',
      },
      sports: {
        all: 'Всі види спорту',
        tennis: 'Теніс',
        badminton: 'Бадмінтон',
        footballField: 'Футбольне поле',
        box: 'Бокс',
        pingPong: 'Настільний теніс',
        biliard: 'Більярд',
        basketball: 'Баскетбол',
      },
      inputSection: {
        searchPlaceholder: 'Введіть назву клубу або адресу',
        searchBtn: 'Пошук',
        searchHint: 'Натисни «Пошук», якщо не хочеш вибирати фільтри — подивишся всі варіанти',
      },
      bookingsUser: {
        myBookings: 'Мої бронювання',
        noBookings: 'У вас немає активних бронювань',
        useSearch: 'Скористайтесь пошуком, щоб знайти майданчик для гри',
        loading: 'Завантаження...',
        confirmCancel: 'Ви впевнені, що хочете скасувати це бронювання?',
        cancelError: 'Не вдалося скасувати бронювання. Спробуйте ще раз.',
      },
      bookingModal: {
        confirmationTitle: 'Підтвердження бронювання',
        location: 'Локація:',
        sportType: 'Вид спорту:',
        time: 'Час:',
        cost: 'Вартість:',
        comment: 'Коментар:',
        noComment: 'Коментаря немає',
        notice: 'Клуб може змінити вартість послуги',
        close: 'Закрити',
        bookTitle: 'Бронювання',
        chooseSport: 'Вид спорту',
        chooseSportPlaceholder: 'Оберіть вид спорту',
        chooseCourtNumber: 'Номер корту / столу / місця',
        chooseNumberPlaceholder: 'Оберіть номер',
        date: 'Дата',
        chooseDatePlaceholder: 'Оберіть дату',
        timeLabel: 'Час (1 година)',
        chooseTimePlaceholder: 'Оберіть час',
        confirmBooking: 'Підтвердити бронювання',
        cancel: 'Скасувати',
        selectDateError: 'Оберіть дату',
        selectSportError: 'Оберіть вид спорту',
        selectTimeError: 'Оберіть час',
        selectInstanceError: 'Оберіть номер',
        noSlots: 'Немає вільних слотів для цього типу/місця',
        timeTaken: 'Цей час уже заброньовано',
        fullName: "Ім'я та прізвище",
        phone: 'Телефон',
        commentOptional: 'Коментар (необов’язково)',
        costLabel: 'Вартість:',
        submit: 'Підтвердити бронювання',
        processing: 'Обробка...',
        guestPhoneError: 'Телефон повинен починатися з +380 і мати 12 цифр',
        guestNameError: 'Будь ласка, введіть ваше ім’я',
      },
      profileModal: {
        title: 'Профіль користувача',
        fullNameLabel: 'ПІБ:',
        emailLabel: 'Email:',
        phoneLabel: 'Телефон:',
        roleLabel: 'Роль:',
        createdLabel: 'Створено:',
        userRole: 'Користувач',
        adminRole: 'Адміністратор Майданчика',
        change: 'Змінити',
        close: 'Закрити',
      },
      courtCard: {
        noCommission: '❤️ Без комісії',
        online: '⚡ Онлайн',
        bookFast: 'У цьому клубі можна забронювати корт менше ніж за 1 хвилину',
        bookButton: '⚡ Забронювати майданчик у кілька кліків тут →',
        book: 'Забронювати',
        showOnMap: 'Показати на карті',
      },
      common: {
        anyTime: 'Будь-який час',
        loading: 'Завантаження...',
        error: 'Сталася помилка',
        cancel: 'Скасувати',
      },
      citySelector: {
        inCity: ' в м.',
      },
      results: {
        found: 'Ми знайшли',
      },
    },
    en: {
      header: { home: 'Home page', contacts: 'Contacts', loginBtn: 'Log In', signupBtn: 'Start for free', logoText: 'mikitchTask', myProfile: 'My profile ▼', profile: 'Profile', myBookings: 'My bookings', allBookings: 'All bookings', logout: 'Logout' },
      theme: {
  light: 'Light',
  dark: 'Dark',
  switchToLight: 'Switch to light theme',
  switchToDark: 'Switch to dark theme'
},
      login: { title: 'Log In', invalidCredentials: 'Invalid email or password', noAccount: "Don't have an account?", register: 'Register' },
      register: { title: 'Create account', alreadyHaveAccount: 'Already have an account?', login: 'Log In' },
      footer: { subscribe: 'Subscribe to our newsletter for the latest features and updates.', emailPlaceholder: 'Your email here', join: 'Join', consent: 'By subscribing, you consent to our Privacy Policy and receive updates.', usefulLinks: 'Useful Links', aboutUs: 'About Us', contactUs: 'Contact Us', support: 'Support', careers: 'Careers', blog: 'Blog', resources: 'Resources', helpCenter: 'Help Center', apiDocs: 'API Docs', community: 'Community', feedback: 'Feedback', events: 'Events', connectWithUs: 'Connect With Us', copyright: '© 2025 Relume. All rights reserved.', privacy: 'Privacy Policy', terms: 'Terms of Service', cookie: 'Cookie Settings' },
      sports: { all: 'All kinds of sport', tennis: 'Tennis', badminton: 'Badminton', footballField: 'Football field', box: 'Box', pingPong: 'Ping Pong', biliard: 'Billiards', basketball: 'Basketball' },
      inputSection: { searchPlaceholder: 'Enter club name or address', searchBtn: 'Search', searchHint: 'Click «Search» if you don’t want to select filters — you will see all options' },
      bookingsUser: { myBookings: 'My bookings', noBookings: 'You have no active bookings', useSearch: 'Use search to find a court', loading: 'Loading...', confirmCancel: 'Are you sure you want to cancel this booking?', cancelError: 'Failed to cancel booking. Try again.' },
      bookingModal: { confirmationTitle: 'Booking confirmation', location: 'Location:', sportType: 'Sport type:', time: 'Time:', cost: 'Cost:', comment: 'Comment:', noComment: 'No comment', notice: 'The club may change the service cost', close: 'Close', bookTitle: 'Booking', chooseSport: 'Sport type', chooseSportPlaceholder: 'Select sport type', chooseCourtNumber: 'Court / table / place number', chooseNumberPlaceholder: 'Select number', date: 'Date', chooseDatePlaceholder: 'Select date', timeLabel: 'Time (1 hour)', chooseTimePlaceholder: 'Select time', confirmBooking: 'Confirm booking', cancel: 'Cancel', selectDateError: 'Select date', selectSportError: 'Select sport type', selectTimeError: 'Select time', selectInstanceError: 'Select number', noSlots: 'No free slots', timeTaken: 'This time is already booked', fullName: 'Full name', phone: 'Phone', commentOptional: 'Comment (optional)', costLabel: 'Cost:', submit: 'Confirm booking', processing: 'Processing...', guestPhoneError: 'Phone must start with +380 and have 12 digits', guestNameError: 'Please enter your name' },
      profileModal: { title: 'User profile', fullNameLabel: 'Full name:', emailLabel: 'Email:', phoneLabel: 'Phone:', roleLabel: 'Role:', createdLabel: 'Created:', userRole: 'User', adminRole: 'Court Administrator', change: 'Change', close: 'Close' },
      courtCard: { noCommission: '❤️ No commission', online: '⚡ Online', bookFast: 'Book a court in less than 1 minute', bookButton: '⚡ Book a court in a few clicks here →', book: 'Book', showOnMap: 'Show on map' },
      common: { anyTime: 'Any time', loading: 'Loading...', error: 'An error occurred', cancel: 'Cancel' },
      citySelector: { inCity: ' in city' },
      results: { found: 'We found' },
    },
    pl: {
      header: { home: 'Strona główna', contacts: 'Kontakt', loginBtn: 'Zaloguj się', signupBtn: 'Rozpocznij za darmo', logoText: 'mikitchTask', myProfile: 'Mój profil ▼', profile: 'Profil', myBookings: 'Moje rezerwacje', allBookings: 'Wszystkie rezerwacje', logout: 'Wyloguj się' },
      theme: {
  light: 'Jasny',
  dark: 'Ciemny',
  switchToLight: 'Przełącz na jasny motyw',
  switchToDark: 'Przełącz na ciemny motyw'
},
      login: { title: 'Zaloguj się', invalidCredentials: 'Nieprawidłowy email lub hasło', noAccount: 'Nie masz konta?', register: 'Zarejestruj się' },
      register: { title: 'Utwórz konto', alreadyHaveAccount: 'Masz już konto?', login: 'Zaloguj się' },
      footer: { subscribe: 'Zapisz się do newslettera, aby otrzymywać najnowsze funkcje i aktualizacje.', emailPlaceholder: 'Twój email tutaj', join: 'Dołącz', consent: 'Subskrybując, zgadzasz się na naszą Politykę prywatności.', usefulLinks: 'Przydatne linki', aboutUs: 'O nas', contactUs: 'Kontakt z nami', support: 'Wsparcie', careers: 'Kariera', blog: 'Blog', resources: 'Zasoby', helpCenter: 'Centrum pomocy', apiDocs: 'Dokumentacja API', community: 'Społeczność', feedback: 'Opinie', events: 'Wydarzenia', connectWithUs: 'Połącz się z nami', copyright: '© 2025 Relume. Wszystkie prawa zastrzeżone.', privacy: 'Polityka prywatności', terms: 'Warunki usługi', cookie: 'Ustawienia ciasteczek' },
      sports: { all: 'Wszystkie rodzaje sportu', tennis: 'Tenis', badminton: 'Badminton', footballField: 'Boisko piłkarskie', box: 'Boks', pingPong: 'Ping-pong', biliard: 'Bilard', basketball: 'Koszykówka' },
      inputSection: { searchPlaceholder: 'Wpisz nazwę klubu lub adres', searchBtn: 'Szukaj', searchHint: 'Kliknij «Szukaj», jeśli nie chcesz wybierać filtrów — zobaczysz wszystkie opcje' },
      bookingsUser: { myBookings: 'Moje rezerwacje', noBookings: 'Nie masz aktywnych rezerwacji', useSearch: 'Skorzystaj z wyszukiwania, aby znaleźć boisko', loading: 'Ładowanie...', confirmCancel: 'Czy na pewno chcesz anulować rezerwację?', cancelError: 'Nie udało się anulować rezerwacji.' },
      bookingModal: { confirmationTitle: 'Potwierdzenie rezerwacji', location: 'Lokalizacja:', sportType: 'Rodzaj sportu:', time: 'Czas:', cost: 'Koszt:', comment: 'Komentarz:', noComment: 'Brak komentarza', notice: 'Klub może zmienić koszt usługi', close: 'Zamknij', bookTitle: 'Rezerwacja', chooseSport: 'Rodzaj sportu', chooseSportPlaceholder: 'Wybierz rodzaj sportu', chooseCourtNumber: 'Numer kortu / stołu / miejsca', chooseNumberPlaceholder: 'Wybierz numer', date: 'Data', chooseDatePlaceholder: 'Wybierz datę', timeLabel: 'Czas (1 godzina)', chooseTimePlaceholder: 'Wybierz czas', confirmBooking: 'Potwierdź rezerwację', cancel: 'Anuluj', selectDateError: 'Wybierz datę', selectSportError: 'Wybierz rodzaj sportu', selectTimeError: 'Wybierz czas', selectInstanceError: 'Wybierz numer', noSlots: 'Brak wolnych slotów', timeTaken: 'Ten czas jest już zarezerwowany', fullName: 'Imię i nazwisko', phone: 'Telefon', commentOptional: 'Komentarz (opcjonalny)', costLabel: 'Koszt:', submit: 'Potwierdź rezerwację', processing: 'Przetwarzanie...', guestPhoneError: 'Telefon musi zaczynać się od +380 i mieć 12 cyfr', guestNameError: 'Proszę wprowadzić imię' },
      profileModal: { title: 'Profil użytkownika', fullNameLabel: 'Imię i nazwisko:', emailLabel: 'Email:', phoneLabel: 'Telefon:', roleLabel: 'Rola:', createdLabel: 'Utworzono:', userRole: 'Użytkownik', adminRole: 'Administrator boiska', change: 'Zmień', close: 'Zamknij' },
      courtCard: { noCommission: '❤️ Bez prowizji', online: '⚡ Online', bookFast: 'Możesz zarezerwować kort w mniej niż 1 minutę', bookButton: '⚡ Zarezerwuj boisko w kilka kliknięć tutaj →', book: 'Zarezerwuj', showOnMap: 'Pokaż na mapie' },
      common: { anyTime: 'Dowolny czas', loading: 'Ładowanie...', error: 'Wystąpił błąd', cancel: 'Anuluj' },
      citySelector: { inCity: ' w m.' },
      results: { found: 'Znaleźliśmy' },
    },
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};